name: Deploy Angular to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'inbentory_app/stock-app/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd inbentory_app/stock-app
        npm install
        
    - name: Build Angular app
      run: |
        cd inbentory_app/stock-app
        npm run build:spa
        
    - name: Copy necessary files to build output
      run: |
        cd inbentory_app/stock-app
        cp src/web.config dist/stock-app/browser/ || echo "web.config not found or already copied"
        cp server.js dist/stock-app/
        cp package.json dist/stock-app/
        cp package-lock.json dist/stock-app/
        
    - name: List build output
      run: |
        cd inbentory_app/stock-app
        echo "=== Build output directory structure ==="
        find dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -10
        echo "=== Browser directory contents ==="
        ls -la dist/stock-app/browser/
        echo "=== Index.html content preview ==="
        head -20 dist/stock-app/browser/index.html
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-web-yumi-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        package: './inbentory_app/stock-app/dist/stock-app'
        
    - name: Configure App Service for SPA
      run: |
        az webapp config set --resource-group 99TEST --name inventory-web-yumi-dev --startup-file ""
        az webapp config appsettings set --resource-group 99TEST --name inventory-web-yumi-dev --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false WEBSITE_NODE_DEFAULT_VERSION=20.x
