name: Deploy Angular to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'inbentory_app/stock-app/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd inbentory_app/stock-app
        npm install
        
    - name: Build Angular app
      run: |
        cd inbentory_app/stock-app
        npm run build:spa
        
    - name: Create server.js for Azure deployment
      run: |
        cd inbentory_app/stock-app
        cat > dist/stock-app/server.js << 'EOF'
        const express = require('express');
        const path = require('path');
        const app = express();

        // 静的ファイルの配信
        app.use(express.static(path.join(__dirname, 'browser')));

        // SPA用のフォールバック - すべてのルートをindex.htmlにリダイレクト
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'browser/index.html'));
        });

        const port = process.env.PORT || 8080;
        app.listen(port, () => {
          console.log(`Server running on port ${port}`);
        });
        EOF
        
    - name: Create production package.json
      run: |
        cd inbentory_app/stock-app
        cat > dist/stock-app/package.json << 'EOF'
        {
          "name": "stock-app",
          "version": "0.0.0",
          "scripts": {
            "start": "node server.js"
          },
          "dependencies": {
            "express": "^5.1.0"
          }
        }
        EOF
        
    - name: Install production dependencies
      run: |
        cd inbentory_app/stock-app/dist/stock-app
        npm install --production
        
    - name: Copy web.config if exists
      run: |
        cd inbentory_app/stock-app
        if [ -f src/web.config ]; then cp src/web.config dist/stock-app/browser/; fi
        
    - name: List build output
      run: |
        cd inbentory_app/stock-app
        echo "=== Final deployment structure ==="
        ls -la dist/stock-app/
        echo "=== Browser directory contents ==="
        ls -la dist/stock-app/browser/
        echo "=== Server.js content ==="
        cat dist/stock-app/server.js
        echo "=== Package.json content ==="
        cat dist/stock-app/package.json
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-web-yumi-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        package: './inbentory_app/stock-app/dist/stock-app'
