name: Deploy Angular to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'stock-app/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'stock-app/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd stock-app
        npm ci
        
    - name: Build Angular app
      run: |
        cd stock-app
        npm run build --prod
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'inventory-web-yumi-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        package: 'stock-app/dist'
